<html> 
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="/css/voka_int.css">
{{#PROPERTY}}
</head>
<body>
<table width="100%" height="50" id="feature_TABLE" class="mainfont">
	<tr>
		<th height="10" valign="middle" bgcolor="#E6E6E6" >Property</th>
	</tr>
	<tr>
		<td class="mainfont" height="10" >
		<strong ><em>Address: </em></strong>{{PROPERTY_RPROPAD}}
		</td>
	</tr>
	<tr>
		<td class="mainfont" height="10" >
		<strong ><em>Acreage: </em></strong>{{PROPERTY_RACRE}}
		</td>
	</tr>
	<tr>
		<td class="mainfont" height="10" >
		<strong ><em>Owner: </em></strong>{{PROPERTY_RNAME}}
		</td>
	</tr>
	<tr>
		<td class="mainfont" height="10" >
		<strong ><em>Zone: </em></strong>{{PROPERTY_RTYPE}}
		</td>
	</tr>
	<tr>
		<td class="mainfont" height="10" ><strong>Lot Size: </strong></em>{{PROPERTY_RLOT}}</td>
	</tr>
	<tr>
		<td class="mainfont" height="10" ><a target="_blank" href="/rest/data/Property/{{PROPERTY_Autogenerated_SDF_ID}}.html">Property Report</a></strong></em></td>
	</tr>
	</table>

{{/PROPERTY}}
</td>
</tr>
</table>
</body>
</html>